openapi: 3.0.1
info:
  title: FacultyLeave API Specification
  description: The API Specification for Texas A&M Libraries FacultyLeave Application
  contact:
    email: tamulib-admin@library.tamu.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://github.com/TAMULib/FacultyLeave
paths:
  /leave:
    get:
      tags:
      - leave
      summary: Get a list of requests for leave
      description: Get a list of requests for leave
      operationId: getLeave
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: ids
        in: query
        description: Comma separated string of leave request ids
        schema:
          type: string
      - name: departmentName
        in: query
        description: The name of the department to retrieve requests for
        schema:
          type: string
      - name: timeframe
        in: query
        description: The window of time for requests
        schema:
          type: string
      responses:
        200:
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Leave'
        400:
          description: The request was invalid
          content: {}
        500:
          description: Internal Server Error
          content: {}
    post:
      tags:
      - leave
      summary: Add a new request for leave
      description: Add a new request for leave
      operationId: addLeave
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      requestBody:
        description: Leave object describing the requested leave
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Leave'
        required: true
      responses:
        201:
          description: Leave Request Created
          content: {}
        401:
          description: You are not authorized to create a leave request
          content: {}
        403:
          description: You are forbidden to create a leave request
          content: {}
        422:
          description: The requested leave is an unprocessable entity
          content: {}
        500:
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /leave/{id}:
    get:
      tags:
      - leave
      summary: Get a request for leave by id
      description: Get a request for leave by id
      operationId: getLeaveById
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: id
        in: path
        description: ID of leave request to be updated
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Request successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Leave'
        400:
          description: The request was invalid
          content: {}
        404:
          description: The leave request was not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
    put:
      tags:
      - leave
      summary: Update an existing leave request
      description: Update an existing leave request
      operationId: updateLeave
      security:
        - spring_session: [
          WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: id
        in: path
        description: ID of leave request to be updated
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        description: Leave object used to update existing leave request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Leave'
        required: true
      responses:
        204:
          description: Leave Request Updated
          content: {}
        401:
          description: You are not authorized to create a leave request
          content: {}
        403:
          description: You are forbidden to create a leave request
          content: {}
        404:
          description: Leave request not found
          content: {}
        422:
          description: The requested leave is an unprocessable entity
          content: {}
        500:
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /leave/{id}/approve:
    put:
      tags:
      - leave
      summary: Modify a leave request with approval
      description: Modify a leave request with approval
      operationId: updateLeaveApproval
      security:
        - spring_session: [
          WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        204:
          description: The leave request has been approved
          content: {}
        401:
          description: You are not authorized to approve a leave request
          content: {}
        403:
          description: You are forbidden to approve a leave request
          content: {}
        404:
          description: Leave request not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /leave/{id}/reject:
    put:
      tags:
      - leave
      summary: Modify a leave request with rejection
      description: Modify a leave request with rejection
      operationId: updateLeaveRejection
      security:
        - spring_session: [
          WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        204:
          description: The leave request has been rejected
          content: {}
        401:
          description: You are not authorized to reject a leave request
          content: {}
        403:
          description: You are forbidden to reject a leave request
          content: {}
        404:
          description: Leave request not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /leave/{id}/cancel:
    put:
      tags:
      - leave
      summary: Cancels a leave request
      description: Cancels a leave request
      operationId: cancelLeaveRequest
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        204:
          description: The leave request has been canceled
          content: {}
        401:
          description: You are not authorized to cancel a leave request
          content: {}
        403:
          description: You are forbidden to cancel a leave request
          content: {}
        404:
          description: Leave request not found
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /leave/{id}/correction:
    post:
      tags:
      - leave
      summary: Request a correction for an existing request for leave
      description: Request a correction for an existing request for leave
      operationId: correctLeave
      security:
        - spring_session: [
          Employee
        ]
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        description: PastLeaveChangeRequest object describing the requested changes
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PastLeaveChangeRequest'
        required: true
      responses:
        201:
          description: Correction Request Created
          content: {}
        401:
          description: You are not authorized to create a correction request
          content: {}
        403:
          description: You are forbidden to create a correction request
          content: {}
        422:
          description: The requested leave is an unprocessable entity
          content: {}
        500:
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /employees/{netId}:
    get:
      tags:
      - employees
      summary: Retrieves an employee by UIN
      description: Retrieves an employee by UIN
      operationId: getEmployee
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: netId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Employee Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        401:
          description: You are not authorized to retrieve an employee
          content: {}
        403:
          description: You are forbidden to retrieve an employee
          content: {}
        404:
          description: Employee Not Found
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /employees/{netId}/leave:
    get:
      tags:
      - employees
      summary: Retrieves a list of an employee's requested leave by netId
      description: Retrieves a list of an employee's requested leave by netId
      operationId: getEmployeeLeave
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: netId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Employee Leave Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Leave'
        401:
          description: You are not authorized to retrieve an employee's leave
          content: {}
        403:
          description: You are forbidden to retrieve an employee's leave
          content: {}
        404:
          description: Employee Not Found
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /employees/{netId}/history:
    get:
      tags:
      - employees
      summary: Retrieves an employee's leave history
      description: Retrieves an employee's leave history
      operationId: getEmployeeHistory
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: netId
        in: path
        required: true
        schema:
          type: string
      - name: timeframe
        in: query
        description: The window of time for requests
        schema:
          type: string
      responses:
        200:
          description: Employee Leave History Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Leave'
        401:
          description: You are not authorized to retrieve an employee's leave history
          content: {}
        403:
          description: You are forbidden to retrieve an employee's leave history
          content: {}
        404:
          description: Employee Not Found
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /employees/{netId}/balance:
    get:
      tags:
      - employees
      summary: Retrieves an employee's leave balance
      description: Retrieves an employee's leave balance
      operationId: getEmployeeLeaveBalance
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: netId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Employee Leave Balance Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveBalance'
        401:
          description: You are not authorized to retrieve an employee's leave balance
          content: {}
        403:
          description: You are forbidden to retrieve an employee's leave balance
          content: {}
        404:
          description: Employee Not Found
          content: {}
        500:
          description: Internal Server Error
          content: {}
  /employees/{netId}/settings:
    get:
      tags:
      - employees
      summary: Retrieves an employee's settings
      description: Retrieves an employee's settings
      operationId: getEmployeeSettings
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: netId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Employee Settings Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonProfile'
        401:
          description: You are not authorized to retrieve an employee's settings
          content: {}
        403:
          description: You are forbidden to retrieve an employee's settings
          content: {}
        404:
          description: Employee Not Found
          content: {}
        500:
          description: Internal Server Error
          content: {}
    put:
      tags:
      - employees
      summary: Updates an employee's settings
      description: Updates an employee's settings
      operationId: putEmployeeSettings
      security:
        - spring_session: [
          Employee, WorkAdmin, or HRAdmin
        ]
      parameters:
      - name: netId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonProfile'
        required: true
      responses:
        204:
          description: Employee Settings Updated
          content: {}
        400:
          description: The settings object is invalid
          content: {}
        401:
          description: You are not authorized to update an employee's settings
          content: {}
        403:
          description: You are forbidden to update an employee's settings
          content: {}
        404:
          description: Employee Not Found
          content: {}
        422:
          description: The settings object is an unprocessable entity
          content: {}
        500:
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: settings
components:
  schemas:
    Leave:
      required:
      - days
      - title
      - description
      - employeeNetId
      - supervisorNetId
      - isApproved
      type: object
      properties:
        days:
          type: array
          items:
            $ref: '#/components/schemas/LeaveDay'
        title:
          type: string
          example: June Leave
        description:
          type: string
          example: Summer Vacation
        employeeNetId:
          type: string
        supervisorNetId:
          type: string
        isApproved:
          type: boolean
    LeaveDay:
      required:
      - date
      - leaveDayDuration
      type: object
      properties:
        leaveDayDuration:
          type: string
          enum:
          - HALF
          - FULL
        date:
          type: string
          format: date
          example: 0005-11-21
    PastLeaveChangeRequest:
      required:
      - description
      type: object
      properties:
        referencedLeave:
          type: string
          format: uuid
        description:
          type: string
    Person:
      type: object
      properties:
        role:
          type: string
          enum:
          - EMPLOYEE
          - WORK_ADMIN
          - HR_ADMIN
        netId:
          type: string
        email:
          type: string
        displayName:
          type: string
        department:
          type: string
        title:
          type: string
        position:
          type: string
        supervisor:
          $ref: '#/components/schemas/Person'
        reports:
          type: array
          items:
            $ref: '#/components/schemas/Person'
    PersonProfile:
      type: object
      properties:
        netId:
          type: string
        futureLeaveColor:
          type: string
        pastLeaveColor:
          type: string
        preferredColors:
          type: array
          items:
            type: string
        preferDayDisplay:
          type: boolean
        ChosenReports:
          type: array
          items:
            $ref: '#/components/schemas/Person'
    LeaveBalance:
      type: object
      properties:
        total:
          type: number
          format: float
  securitySchemes:
    spring_session:
      type: http
      in: cookie
      name: JSESSIONID
