swagger: "2.0"
info:
  description: "The API Specefication for Texas A&M Libraries FacultyLeave Application"
  version: "1.0.0"
  title: "FacultyLeave API Specefication"
  contact:
    email: "tamulib-admin@library.tamu.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "github.com"
basePath: "/TAMULib/FacultyLeave"
schemes:
- "https"
- "http"
paths:
  /leave:
    post:
      tags:
      - "leave"
      summary: "Add a new request for leave."
      description: "Add a new request for leave."
      operationId: "addLeave"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        description: "Leave object describing the requested leave."
        required: true
        schema:
          $ref: "#/definitions/Leave"
      responses:
        "201":
          description: "Leave Request Created"
        "401":
          description: "You are not authorized to create a leave request"
        "403":
          description: "You are forbidden to create a leave request"
        "422":
          description: "The requested leave is an unprocessable entity"
        "500":
          description: "Internal Server Error"
    get:
      tags:
      - "leave"
      summary: "Get a list of requests for leave."
      description: "Get a list of requests for leave."
      operationId: "getLeave"
      produces:
      - "application/json"
      parameters:
      - name: "ids"
        in: "query"
        description: "Comma seperated string of ids to return"
        required: false
        type: "string"
      - name: "departmentName"
        in: "query"
        description: "The name of the department to retrieve requests for"
        required: false
        type: "string"
      - name: "timeframe"
        in: "query"
        description: "The window of time for requests"
        required: false
        type: "string"
      responses:
        "200":
          description: "Request successful"
        "400":
          description: "The request was invalid"
        "500":
          description: "Internal Server Error"
  /leave/{id}:
    put:
      tags:
      - "leave"
      summary: "Update an existing leave request"
      description: "Update an existing leave request"
      operationId: "updateLeave"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of leave request to be updated"
        required: true
        type: "string"
        format: "uuid"
      - in: "body"
        name: "body"
        description: "Leave object used to update existing leave request"
        required: true
        schema:
          $ref: "#/definitions/Leave"
      responses:
        "204":
          description: "Leave Request Updated"
        "401":
          description: "You are not authorized to create a leave request"
        "403":
          description: "You are forbidden to create a leave request"
        "404":
          description: "Leave request not found"
        "422":
          description: "The requested leave is an unprocessable entity"
        "500":
          description: "Internal Server Error"
    get:
      tags:
        - "leave"
      summary: "Get a request for leave by id"
      description: "Get a list of requests for leave."
      operationId: "getLeaveById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of leave request to be updated"
        required: true
        type: "string"
        format: "uuid"
      responses:
        "200":
          description: "Request successful"
        "400":
          description: "The request was invalid"
        "404":
          description: "The leave request was not found"
        "500":
          description: "Internal Server Error"
  /leave/{id}/approve:
    put:
      tags:
        - "leave"
      summary: "Modify a leave request with approval."
      description: "Modify a leave request with approval."
      operationId: "updateLeaveApproval"
      consumes:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        "204": 
          description: "The leave request has been approved"
        "401": 
          description: "You are not authorized to approve a leave request"
        "403":
          description: "You are forbidden to approve a leave request"
        "404":
          description: "Leave request not found"
        "500":
          description: "Internal Server Error"
  /leave/{id}/reject:
    put:
      tags:
        - "leave"
      summary: "Modify a leave request with rejection."
      description: "Modify a leave request with approval."
      operationId: "updateLeaveRejection"
      consumes:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        "204": 
          description: "The leave request has been rejected"
        "401": 
          description: "You are not authorized to reject a leave request"
        "403":
          description: "You are forbidden to reject a leave request"
        "404":
          description: "Leave request not found"
        "500":
          description: "Internal Server Error"
  /leave/{id}/cancel:
    put:
      tags:
        - "leave"
      summary: "Cancels a leave request."
      description: "Cancels a leave request."
      operationId: "cancelLeaveRequest"
      consumes:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
      responses:
        "204": 
          description: "The leave request has been canceled"
        "401": 
          description: "You are not authorized to cancel a leave request"
        "403":
          description: "You are forbidden to cancel a leave request"
        "404":
          description: "Leave request not found"
        "500":
          description: "Internal Server Error"
  /leave/{id}/correction:
    post:
      tags:
      - "leave"
      summary: "Add a new corection for an existing request for leave."
      description: "Add a new corection for an existing request for leave."
      operationId: "correctLeave"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
        - name: "body"
          in: "body"
          description: "PastLeaveChangeRequest object describing the requested changes."
          required: true
          schema:
            $ref: "#/definitions/PastLeaveChangeRequest"
      responses:
        "201":
          description: "Leave Request Created"
        "401":
          description: "You are not authorized to create a leave request"
        "403":
          description: "You are forbidden to create a leave request"
        "422":
          description: "The requested leave is an unprocessable entity"
        "500":
          description: "Internal Server Error"
  /pet/findByStatus:
    get:
      tags:
      - "pet"
      summary: "Finds Pets by status"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "findPetsByStatus"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "status"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: true
        type: "array"
        items:
          type: "string"
          enum:
          - "available"
          - "pending"
          - "sold"
          default: "available"
        collectionFormat: "multi"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Leave"
        "400":
          description: "Invalid status value"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      petId:
        type: "integer"
        format: "int64"
      quantity:
        type: "integer"
        format: "int32"
      shipDate:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Order Status"
        enum:
        - "placed"
        - "approved"
        - "delivered"
      complete:
        type: "boolean"
        default: false
    xml:
      name: "Order"
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
    xml:
      name: "User"
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
  Leave:
    type: "object"
    required:
    - "employeeUIN"
    - "supervisorUIN"
    - "description"
    - "title"
    - "isApproved"
    - "days"
    properties:
      employeeUIN:
        type: "string"
        format: "uuid"
      supervisorUIN:
        type: "integer"
        format: "int64"
      description:
        type: "string"
        example: "Summer Vacation"
      title:
        type: "string"
        example: "June Leave"
      isApproved:
        type: "boolean"
      days:
        type: "array"
        items:
          $ref: "#/definitions/LeaveDay"
  LeaveDay:
    type: "object"
    required:
      - "leaveDayDuration"
      - "date"
    properties:
      leaveDayDuration:
        type: string
        enum: [HALF, FULL]
      date:
        type: string
        format: date
        example: "04-23-21"
  PastLeaveChangeRequest:
    type: "object"
    required:
      - "description"
    properties:
      referencedLeave:
        type: "string"
        format: "uuid"
      description:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"